[project]
name = "gcc_graph_tool"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
	"click",
	"mkdocs",
	"mkdocs-material",
	"pre-commit",
	"ruff",
	"ty",
	"pytest",
	"strictyaml",
	"pydantic",
	"pydot",
	"graphviz",
]
